### PR TITLE
chore(Cargo.toml): bump spin crates

### PR DESCRIPTION
**Pull request by vdice**
Bumps to current HEAD commit of Spin, particularly to get https://github.com/fermyon/spin/commit/d041cc0470c39a341de7b709e7cab5e7d5a011ef

Closes https://github.com/fermyon/cloud-plugin/issues/101

### CODE REVIEW

**Comment by itowlson** [comment]
This makes me wonder if we should be flagging the change to folks like the containerd shim maintainers.

**Comment by vdice** [comment]
> This makes me wonder if we should be flagging the change to folks like the containerd shim maintainers.

Ah, in case example or template apps are used from main/canary with the 1.5.0-based shim?

**Comment by itowlson** [comment]
The templates still have `base` (at least for now) so there's a good chance they won't come across it.  But yes, generally, because it's plausible that people will try to run 1.6 apps on k8s and get a surprising error.

I wonder if in future we should consider minor versions of the manifest format for stuff like this - at least then a host could say "hey you need to update me" rather than "missing required element."

**Comment by vdice** [comment]
> I wonder if in future we should consider minor versions of the manifest format for stuff like this - at least then a host could say "hey you need to update me" rather than "missing required element."

That seems like a good idea to me.

**Review by fibonacci1729 — APPROVED** [review]

**Pull request merged**
